### ISSUE TITLE
Use of `programId`, not `owner`

### ISSUE THREAD

**Issue by garious** [solana-labs/example-tictactoe#6]

**Comment by mvines** [comment]
Can you be more specific?   This commit, 
https://github.com/solana-labs/example-tictactoe/commit/50d435c2ca8a45c8c2ff2e60e77b5257385c05da, adapts ttt to the programId -> owner account changes made on master.   There are still instances of programId in ttt but those references are valid in that they don’t refer to the specific account ownership case where we renamed programId to owner

**Comment by garious** [comment]
Yep, error on my end. Thanks for the detailed response.
