### ISSUE TITLE
Error loading BPF program

### ISSUE THREAD

**Issue by ggsonic** [solana-labs/example-tictactoe#7]
do as your doc said, always failed to  do `npm run start`. both local docker and live=1 testnet.

`await BpfLoader.load(connection, loaderAccount, elf);` not working

**Comment by mvines** [comment]
Thanks for the report!  I pushed a couple commits that should resolve this issue:
2b90dc430038b6a934036c16082cc46f968edb99
81e31922a955c9f787990a4cc7ee844f3b90a20b

But note that at the tip of master `LIVE=1` won't work for another couple weeks until we make our next beta channel release.    To use `LIVE=1` until then please use the [v0.0.0  release tag](https://github.com/solana-labs/example-tictactoe/releases/tag/v0.0.0).

If this is still an issue for you please feel free to reopen this issue, thanks!
