### ISSUE TITLE
some readme links are broken

### ISSUE THREAD

**Issue by manuel-calavera** [solana-labs/example-tictactoe#8]
Next links seem broken:

https://github.com/solana-labs/solana/tree/master/programs/bpf/c/sdk#prerequisites
https://github.com/solana-labs/solana/tree/master/programs/bpf/c/sdk/bpf.mk
https://github.com/solana-labs/solana/blob/master/doc/json-rpc.md#getaccountinfo

**Comment by mvines** [comment]
Thanks for filing this!  Fixed at the tip (by 591991a09d0a62284ff5a79c454edfa33b78dffa)
